// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions } from '@tanstack/vue-query';

import { client } from '../client.gen';
import { getSession, listAlertHistory, type Options } from '../sdk.gen';
import type { GetSessionData, GetSessionError, GetSessionResponse, ListAlertHistoryData, ListAlertHistoryError, ListAlertHistoryResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getSessionQueryKey = (options?: Options<GetSessionData>) => createQueryKey('getSession', options);

/**
 * Say who is signed in
 *
 * Returns the admin the session cookie belongs to. A request without a session, or with one auth no longer stands behind, gets a 401: the web app then shows the sign-in page.
 */
export const getSessionOptions = (options?: Options<GetSessionData>) => queryOptions<GetSessionResponse, GetSessionError, GetSessionResponse, ReturnType<typeof getSessionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSession({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSessionQueryKey(options)
});

export const listAlertHistoryQueryKey = (options?: Options<ListAlertHistoryData>) => createQueryKey('listAlertHistory', options);

/**
 * List the states alerts were seen in, newest first
 *
 * Returns at most `limit` events, newest first. An event is one state of one firing of an alert: it fired, or it resolved. Alertmanager forgets a resolved alert; this is the dashboard's own record.
 */
export const listAlertHistoryOptions = (options?: Options<ListAlertHistoryData>) => queryOptions<ListAlertHistoryResponse, ListAlertHistoryError, ListAlertHistoryResponse, ReturnType<typeof listAlertHistoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAlertHistory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAlertHistoryQueryKey(options)
});
