// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	GetSessionOperation       OperationName = "GetSession"
	ListAlertHistoryOperation OperationName = "ListAlertHistory"
)
