// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
)

func (s *ProblemStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// One state an alert was seen in.
// Ref: #/components/schemas/AlertEvent
type AlertEvent struct {
	// The event's id.
	ID int64 `json:"id"`
	// Alertmanager's fingerprint of the alert.
	Fingerprint string `json:"fingerprint"`
	// The alert's name.
	Name string `json:"name"`
	// The state the alert was seen in.
	Status AlertEventStatus `json:"status"`
	// When this firing of the alert started.
	StartsAt time.Time `json:"startsAt"`
	// When the alert resolved. Present exactly when the status is resolved.
	EndsAt OptDateTime `json:"endsAt"`
	// When the dashboard saw the alert in this state.
	ObservedAt time.Time `json:"observedAt"`
}

// GetID returns the value of ID.
func (s *AlertEvent) GetID() int64 {
	return s.ID
}

// GetFingerprint returns the value of Fingerprint.
func (s *AlertEvent) GetFingerprint() string {
	return s.Fingerprint
}

// GetName returns the value of Name.
func (s *AlertEvent) GetName() string {
	return s.Name
}

// GetStatus returns the value of Status.
func (s *AlertEvent) GetStatus() AlertEventStatus {
	return s.Status
}

// GetStartsAt returns the value of StartsAt.
func (s *AlertEvent) GetStartsAt() time.Time {
	return s.StartsAt
}

// GetEndsAt returns the value of EndsAt.
func (s *AlertEvent) GetEndsAt() OptDateTime {
	return s.EndsAt
}

// GetObservedAt returns the value of ObservedAt.
func (s *AlertEvent) GetObservedAt() time.Time {
	return s.ObservedAt
}

// SetID sets the value of ID.
func (s *AlertEvent) SetID(val int64) {
	s.ID = val
}

// SetFingerprint sets the value of Fingerprint.
func (s *AlertEvent) SetFingerprint(val string) {
	s.Fingerprint = val
}

// SetName sets the value of Name.
func (s *AlertEvent) SetName(val string) {
	s.Name = val
}

// SetStatus sets the value of Status.
func (s *AlertEvent) SetStatus(val AlertEventStatus) {
	s.Status = val
}

// SetStartsAt sets the value of StartsAt.
func (s *AlertEvent) SetStartsAt(val time.Time) {
	s.StartsAt = val
}

// SetEndsAt sets the value of EndsAt.
func (s *AlertEvent) SetEndsAt(val OptDateTime) {
	s.EndsAt = val
}

// SetObservedAt sets the value of ObservedAt.
func (s *AlertEvent) SetObservedAt(val time.Time) {
	s.ObservedAt = val
}

// The state the alert was seen in.
type AlertEventStatus string

const (
	AlertEventStatusFiring   AlertEventStatus = "firing"
	AlertEventStatusResolved AlertEventStatus = "resolved"
)

// AllValues returns all AlertEventStatus values.
func (AlertEventStatus) AllValues() []AlertEventStatus {
	return []AlertEventStatus{
		AlertEventStatusFiring,
		AlertEventStatusResolved,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AlertEventStatus) MarshalText() ([]byte, error) {
	switch s {
	case AlertEventStatusFiring:
		return []byte(s), nil
	case AlertEventStatusResolved:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AlertEventStatus) UnmarshalText(data []byte) error {
	switch AlertEventStatus(data) {
	case AlertEventStatusFiring:
		*s = AlertEventStatusFiring
		return nil
	case AlertEventStatusResolved:
		*s = AlertEventStatusResolved
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// A page of events, newest first.
// Ref: #/components/schemas/AlertHistory
type AlertHistory struct {
	// The events.
	Items []AlertEvent `json:"items"`
}

// GetItems returns the value of Items.
func (s *AlertHistory) GetItems() []AlertEvent {
	return s.Items
}

// SetItems sets the value of Items.
func (s *AlertHistory) SetItems(val []AlertEvent) {
	s.Items = val
}

func (*AlertHistory) listAlertHistoryRes() {}

type ForwardAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *ForwardAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *ForwardAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *ForwardAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *ForwardAuth) SetRoles(val []string) {
	s.Roles = val
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// An RFC 9457 problem detail.
// Ref: #/components/schemas/Problem
type Problem struct {
	// A URI naming the problem type.
	Type string `json:"type"`
	// A short summary of the problem type.
	Title string `json:"title"`
	// The HTTP status code.
	Status int32 `json:"status"`
	// What went wrong in this occurrence.
	Detail OptString `json:"detail"`
}

// GetType returns the value of Type.
func (s *Problem) GetType() string {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *Problem) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Problem) GetStatus() int32 {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *Problem) GetDetail() OptString {
	return s.Detail
}

// SetType sets the value of Type.
func (s *Problem) SetType(val string) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *Problem) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Problem) SetStatus(val int32) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *Problem) SetDetail(val OptString) {
	s.Detail = val
}

// ProblemStatusCode wraps Problem with StatusCode.
type ProblemStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *ProblemStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ProblemStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ProblemStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ProblemStatusCode) SetResponse(val Problem) {
	s.Response = val
}

func (*ProblemStatusCode) listAlertHistoryRes() {}
