// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
)

func (s *ProblemStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// One alert Alertmanager holds now.
// Ref: #/components/schemas/Alert
type Alert struct {
	// Alertmanager's fingerprint of the alert.
	Fingerprint string `json:"fingerprint"`
	// The alert's name, its alertname label.
	Name string `json:"name"`
	// How loudly the alert wakes someone, from its alert_class label. Absent on an alert whose rule
	// carries no class the dashboard knows.
	Class OptAlertClass `json:"class"`
	// The rule's summary annotation, where it carries one.
	Summary OptString `json:"summary"`
	// When this firing of the alert started.
	StartsAt time.Time `json:"startsAt"`
	// Every label of the alert.
	Labels AlertLabels `json:"labels"`
	// The id of every silence that holds the alert quiet now; empty when none does.
	SilencedBy []string `json:"silencedBy"`
}

// GetFingerprint returns the value of Fingerprint.
func (s *Alert) GetFingerprint() string {
	return s.Fingerprint
}

// GetName returns the value of Name.
func (s *Alert) GetName() string {
	return s.Name
}

// GetClass returns the value of Class.
func (s *Alert) GetClass() OptAlertClass {
	return s.Class
}

// GetSummary returns the value of Summary.
func (s *Alert) GetSummary() OptString {
	return s.Summary
}

// GetStartsAt returns the value of StartsAt.
func (s *Alert) GetStartsAt() time.Time {
	return s.StartsAt
}

// GetLabels returns the value of Labels.
func (s *Alert) GetLabels() AlertLabels {
	return s.Labels
}

// GetSilencedBy returns the value of SilencedBy.
func (s *Alert) GetSilencedBy() []string {
	return s.SilencedBy
}

// SetFingerprint sets the value of Fingerprint.
func (s *Alert) SetFingerprint(val string) {
	s.Fingerprint = val
}

// SetName sets the value of Name.
func (s *Alert) SetName(val string) {
	s.Name = val
}

// SetClass sets the value of Class.
func (s *Alert) SetClass(val OptAlertClass) {
	s.Class = val
}

// SetSummary sets the value of Summary.
func (s *Alert) SetSummary(val OptString) {
	s.Summary = val
}

// SetStartsAt sets the value of StartsAt.
func (s *Alert) SetStartsAt(val time.Time) {
	s.StartsAt = val
}

// SetLabels sets the value of Labels.
func (s *Alert) SetLabels(val AlertLabels) {
	s.Labels = val
}

// SetSilencedBy sets the value of SilencedBy.
func (s *Alert) SetSilencedBy(val []string) {
	s.SilencedBy = val
}

// How loudly the alert wakes someone, from its alert_class label. Absent on an alert whose rule
// carries no class the dashboard knows.
type AlertClass string

const (
	AlertClassBusinessHours AlertClass = "business-hours"
	AlertClassUrgent        AlertClass = "urgent"
	AlertClassPage          AlertClass = "page"
)

// AllValues returns all AlertClass values.
func (AlertClass) AllValues() []AlertClass {
	return []AlertClass{
		AlertClassBusinessHours,
		AlertClassUrgent,
		AlertClassPage,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AlertClass) MarshalText() ([]byte, error) {
	switch s {
	case AlertClassBusinessHours:
		return []byte(s), nil
	case AlertClassUrgent:
		return []byte(s), nil
	case AlertClassPage:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AlertClass) UnmarshalText(data []byte) error {
	switch AlertClass(data) {
	case AlertClassBusinessHours:
		*s = AlertClassBusinessHours
		return nil
	case AlertClassUrgent:
		*s = AlertClassUrgent
		return nil
	case AlertClassPage:
		*s = AlertClassPage
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// One state an alert was seen in.
// Ref: #/components/schemas/AlertEvent
type AlertEvent struct {
	// The event's id.
	ID int64 `json:"id"`
	// Alertmanager's fingerprint of the alert.
	Fingerprint string `json:"fingerprint"`
	// The alert's name.
	Name string `json:"name"`
	// The state the alert was seen in.
	Status AlertEventStatus `json:"status"`
	// When this firing of the alert started.
	StartsAt time.Time `json:"startsAt"`
	// When the alert resolved. Present exactly when the status is resolved.
	EndsAt OptDateTime `json:"endsAt"`
	// When the dashboard saw the alert in this state.
	ObservedAt time.Time `json:"observedAt"`
}

// GetID returns the value of ID.
func (s *AlertEvent) GetID() int64 {
	return s.ID
}

// GetFingerprint returns the value of Fingerprint.
func (s *AlertEvent) GetFingerprint() string {
	return s.Fingerprint
}

// GetName returns the value of Name.
func (s *AlertEvent) GetName() string {
	return s.Name
}

// GetStatus returns the value of Status.
func (s *AlertEvent) GetStatus() AlertEventStatus {
	return s.Status
}

// GetStartsAt returns the value of StartsAt.
func (s *AlertEvent) GetStartsAt() time.Time {
	return s.StartsAt
}

// GetEndsAt returns the value of EndsAt.
func (s *AlertEvent) GetEndsAt() OptDateTime {
	return s.EndsAt
}

// GetObservedAt returns the value of ObservedAt.
func (s *AlertEvent) GetObservedAt() time.Time {
	return s.ObservedAt
}

// SetID sets the value of ID.
func (s *AlertEvent) SetID(val int64) {
	s.ID = val
}

// SetFingerprint sets the value of Fingerprint.
func (s *AlertEvent) SetFingerprint(val string) {
	s.Fingerprint = val
}

// SetName sets the value of Name.
func (s *AlertEvent) SetName(val string) {
	s.Name = val
}

// SetStatus sets the value of Status.
func (s *AlertEvent) SetStatus(val AlertEventStatus) {
	s.Status = val
}

// SetStartsAt sets the value of StartsAt.
func (s *AlertEvent) SetStartsAt(val time.Time) {
	s.StartsAt = val
}

// SetEndsAt sets the value of EndsAt.
func (s *AlertEvent) SetEndsAt(val OptDateTime) {
	s.EndsAt = val
}

// SetObservedAt sets the value of ObservedAt.
func (s *AlertEvent) SetObservedAt(val time.Time) {
	s.ObservedAt = val
}

// The state the alert was seen in.
type AlertEventStatus string

const (
	AlertEventStatusFiring   AlertEventStatus = "firing"
	AlertEventStatusResolved AlertEventStatus = "resolved"
)

// AllValues returns all AlertEventStatus values.
func (AlertEventStatus) AllValues() []AlertEventStatus {
	return []AlertEventStatus{
		AlertEventStatusFiring,
		AlertEventStatusResolved,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AlertEventStatus) MarshalText() ([]byte, error) {
	switch s {
	case AlertEventStatusFiring:
		return []byte(s), nil
	case AlertEventStatusResolved:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AlertEventStatus) UnmarshalText(data []byte) error {
	switch AlertEventStatus(data) {
	case AlertEventStatusFiring:
		*s = AlertEventStatusFiring
		return nil
	case AlertEventStatusResolved:
		*s = AlertEventStatusResolved
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// A page of events, newest first.
// Ref: #/components/schemas/AlertHistory
type AlertHistory struct {
	// The events.
	Items []AlertEvent `json:"items"`
}

// GetItems returns the value of Items.
func (s *AlertHistory) GetItems() []AlertEvent {
	return s.Items
}

// SetItems sets the value of Items.
func (s *AlertHistory) SetItems(val []AlertEvent) {
	s.Items = val
}

func (*AlertHistory) listAlertHistoryRes() {}

// Every label of the alert.
type AlertLabels map[string]string

func (s *AlertLabels) init() AlertLabels {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// The alerts firing now, newest first.
// Ref: #/components/schemas/AlertList
type AlertList struct {
	// The alerts.
	Items []Alert `json:"items"`
}

// GetItems returns the value of Items.
func (s *AlertList) GetItems() []Alert {
	return s.Items
}

// SetItems sets the value of Items.
func (s *AlertList) SetItems(val []Alert) {
	s.Items = val
}

func (*AlertList) listAlertsRes() {}

type ListAlertsServiceUnavailable ProblemStatusCode

func (*ListAlertsServiceUnavailable) listAlertsRes() {}

type ListAlertsUnauthorized ProblemStatusCode

func (*ListAlertsUnauthorized) listAlertsRes() {}

// NewOptAlertClass returns new OptAlertClass with value set to v.
func NewOptAlertClass(v AlertClass) OptAlertClass {
	return OptAlertClass{
		Value: v,
		Set:   true,
	}
}

// OptAlertClass is optional AlertClass.
type OptAlertClass struct {
	Value AlertClass
	Set   bool
}

// IsSet returns true if OptAlertClass was set.
func (o OptAlertClass) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAlertClass) Reset() {
	var v AlertClass
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAlertClass) SetTo(v AlertClass) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAlertClass) Get() (v AlertClass, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAlertClass) Or(d AlertClass) AlertClass {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// An RFC 9457 problem detail.
// Ref: #/components/schemas/Problem
type Problem struct {
	// A URI naming the problem type.
	Type string `json:"type"`
	// A short summary of the problem type.
	Title string `json:"title"`
	// The HTTP status code.
	Status int32 `json:"status"`
	// What went wrong in this occurrence.
	Detail OptString `json:"detail"`
}

// GetType returns the value of Type.
func (s *Problem) GetType() string {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *Problem) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Problem) GetStatus() int32 {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *Problem) GetDetail() OptString {
	return s.Detail
}

// SetType sets the value of Type.
func (s *Problem) SetType(val string) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *Problem) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Problem) SetStatus(val int32) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *Problem) SetDetail(val OptString) {
	s.Detail = val
}

// ProblemStatusCode wraps Problem with StatusCode.
type ProblemStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *ProblemStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ProblemStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ProblemStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ProblemStatusCode) SetResponse(val Problem) {
	s.Response = val
}

func (*ProblemStatusCode) getSessionRes()       {}
func (*ProblemStatusCode) listAlertHistoryRes() {}

// The signed-in admin.
// Ref: #/components/schemas/Session
type Session struct {
	// The account's id in auth.
	Subject string `json:"subject"`
	// What to call the admin, which is the account's username.
	Name string `json:"name"`
}

// GetSubject returns the value of Subject.
func (s *Session) GetSubject() string {
	return s.Subject
}

// GetName returns the value of Name.
func (s *Session) GetName() string {
	return s.Name
}

// SetSubject sets the value of Subject.
func (s *Session) SetSubject(val string) {
	s.Subject = val
}

// SetName sets the value of Name.
func (s *Session) SetName(val string) {
	s.Name = val
}

func (*Session) getSessionRes() {}

type SessionCookie struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *SessionCookie) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *SessionCookie) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *SessionCookie) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *SessionCookie) SetRoles(val []string) {
	s.Roles = val
}

// A silence the dashboard set in Alertmanager.
// Ref: #/components/schemas/Silence
type Silence struct {
	// Alertmanager's id of the silence.
	ID string `json:"id"`
	// The silenced alert's fingerprint.
	Fingerprint string `json:"fingerprint"`
	// The admin who set it.
	CreatedBy string `json:"createdBy"`
	// When it was set.
	CreatedAt time.Time `json:"createdAt"`
	// When it ends. Absent on a silence that lasts until the alert resolves.
	EndsAt OptDateTime `json:"endsAt"`
}

// GetID returns the value of ID.
func (s *Silence) GetID() string {
	return s.ID
}

// GetFingerprint returns the value of Fingerprint.
func (s *Silence) GetFingerprint() string {
	return s.Fingerprint
}

// GetCreatedBy returns the value of CreatedBy.
func (s *Silence) GetCreatedBy() string {
	return s.CreatedBy
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Silence) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetEndsAt returns the value of EndsAt.
func (s *Silence) GetEndsAt() OptDateTime {
	return s.EndsAt
}

// SetID sets the value of ID.
func (s *Silence) SetID(val string) {
	s.ID = val
}

// SetFingerprint sets the value of Fingerprint.
func (s *Silence) SetFingerprint(val string) {
	s.Fingerprint = val
}

// SetCreatedBy sets the value of CreatedBy.
func (s *Silence) SetCreatedBy(val string) {
	s.CreatedBy = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Silence) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetEndsAt sets the value of EndsAt.
func (s *Silence) SetEndsAt(val OptDateTime) {
	s.EndsAt = val
}

func (*Silence) silenceAlertRes() {}

type SilenceAlertBadRequest ProblemStatusCode

func (*SilenceAlertBadRequest) silenceAlertRes() {}

type SilenceAlertNotFound ProblemStatusCode

func (*SilenceAlertNotFound) silenceAlertRes() {}

type SilenceAlertServiceUnavailable ProblemStatusCode

func (*SilenceAlertServiceUnavailable) silenceAlertRes() {}

// How long to silence an alert for.
// Ref: #/components/schemas/SilenceRequest
type SilenceRequest struct {
	// An hour, four hours, a day, or until the alert resolves.
	Length SilenceRequestLength `json:"length"`
}

// GetLength returns the value of Length.
func (s *SilenceRequest) GetLength() SilenceRequestLength {
	return s.Length
}

// SetLength sets the value of Length.
func (s *SilenceRequest) SetLength(val SilenceRequestLength) {
	s.Length = val
}

// An hour, four hours, a day, or until the alert resolves.
type SilenceRequestLength string

const (
	SilenceRequestLength1h            SilenceRequestLength = "1h"
	SilenceRequestLength4h            SilenceRequestLength = "4h"
	SilenceRequestLength1d            SilenceRequestLength = "1d"
	SilenceRequestLengthUntilResolved SilenceRequestLength = "until-resolved"
)

// AllValues returns all SilenceRequestLength values.
func (SilenceRequestLength) AllValues() []SilenceRequestLength {
	return []SilenceRequestLength{
		SilenceRequestLength1h,
		SilenceRequestLength4h,
		SilenceRequestLength1d,
		SilenceRequestLengthUntilResolved,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SilenceRequestLength) MarshalText() ([]byte, error) {
	switch s {
	case SilenceRequestLength1h:
		return []byte(s), nil
	case SilenceRequestLength4h:
		return []byte(s), nil
	case SilenceRequestLength1d:
		return []byte(s), nil
	case SilenceRequestLengthUntilResolved:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SilenceRequestLength) UnmarshalText(data []byte) error {
	switch SilenceRequestLength(data) {
	case SilenceRequestLength1h:
		*s = SilenceRequestLength1h
		return nil
	case SilenceRequestLength4h:
		*s = SilenceRequestLength4h
		return nil
	case SilenceRequestLength1d:
		*s = SilenceRequestLength1d
		return nil
	case SilenceRequestLengthUntilResolved:
		*s = SilenceRequestLengthUntilResolved
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
