// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
)

func (s *ProblemStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// One alert Alertmanager holds now.
// Ref: #/components/schemas/Alert
type Alert struct {
	// Alertmanager's fingerprint of the alert.
	Fingerprint string `json:"fingerprint"`
	// The alert's name, its alertname label.
	Name string `json:"name"`
	// How loudly the alert wakes someone, from its alert_class label. Absent on an alert whose rule
	// carries no class the dashboard knows.
	Class OptAlertClass `json:"class"`
	// The rule's summary annotation, where it carries one.
	Summary OptString `json:"summary"`
	// When this firing of the alert started.
	StartsAt time.Time `json:"startsAt"`
	// Every label of the alert.
	Labels AlertLabels `json:"labels"`
	// The id of every silence that holds the alert quiet now; empty when none does.
	SilencedBy []string `json:"silencedBy"`
}

// GetFingerprint returns the value of Fingerprint.
func (s *Alert) GetFingerprint() string {
	return s.Fingerprint
}

// GetName returns the value of Name.
func (s *Alert) GetName() string {
	return s.Name
}

// GetClass returns the value of Class.
func (s *Alert) GetClass() OptAlertClass {
	return s.Class
}

// GetSummary returns the value of Summary.
func (s *Alert) GetSummary() OptString {
	return s.Summary
}

// GetStartsAt returns the value of StartsAt.
func (s *Alert) GetStartsAt() time.Time {
	return s.StartsAt
}

// GetLabels returns the value of Labels.
func (s *Alert) GetLabels() AlertLabels {
	return s.Labels
}

// GetSilencedBy returns the value of SilencedBy.
func (s *Alert) GetSilencedBy() []string {
	return s.SilencedBy
}

// SetFingerprint sets the value of Fingerprint.
func (s *Alert) SetFingerprint(val string) {
	s.Fingerprint = val
}

// SetName sets the value of Name.
func (s *Alert) SetName(val string) {
	s.Name = val
}

// SetClass sets the value of Class.
func (s *Alert) SetClass(val OptAlertClass) {
	s.Class = val
}

// SetSummary sets the value of Summary.
func (s *Alert) SetSummary(val OptString) {
	s.Summary = val
}

// SetStartsAt sets the value of StartsAt.
func (s *Alert) SetStartsAt(val time.Time) {
	s.StartsAt = val
}

// SetLabels sets the value of Labels.
func (s *Alert) SetLabels(val AlertLabels) {
	s.Labels = val
}

// SetSilencedBy sets the value of SilencedBy.
func (s *Alert) SetSilencedBy(val []string) {
	s.SilencedBy = val
}

// How loudly the alert wakes someone, from its alert_class label. Absent on an alert whose rule
// carries no class the dashboard knows.
type AlertClass string

const (
	AlertClassBusinessHours AlertClass = "business-hours"
	AlertClassUrgent        AlertClass = "urgent"
	AlertClassPage          AlertClass = "page"
)

// AllValues returns all AlertClass values.
func (AlertClass) AllValues() []AlertClass {
	return []AlertClass{
		AlertClassBusinessHours,
		AlertClassUrgent,
		AlertClassPage,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AlertClass) MarshalText() ([]byte, error) {
	switch s {
	case AlertClassBusinessHours:
		return []byte(s), nil
	case AlertClassUrgent:
		return []byte(s), nil
	case AlertClassPage:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AlertClass) UnmarshalText(data []byte) error {
	switch AlertClass(data) {
	case AlertClassBusinessHours:
		*s = AlertClassBusinessHours
		return nil
	case AlertClassUrgent:
		*s = AlertClassUrgent
		return nil
	case AlertClassPage:
		*s = AlertClassPage
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// One state an alert was seen in.
// Ref: #/components/schemas/AlertEvent
type AlertEvent struct {
	// The event's id.
	ID int64 `json:"id"`
	// Alertmanager's fingerprint of the alert.
	Fingerprint string `json:"fingerprint"`
	// The alert's name.
	Name string `json:"name"`
	// The state the alert was seen in.
	Status AlertEventStatus `json:"status"`
	// When this firing of the alert started.
	StartsAt time.Time `json:"startsAt"`
	// When the alert resolved. Present exactly when the status is resolved.
	EndsAt OptDateTime `json:"endsAt"`
	// When the dashboard saw the alert in this state.
	ObservedAt time.Time `json:"observedAt"`
}

// GetID returns the value of ID.
func (s *AlertEvent) GetID() int64 {
	return s.ID
}

// GetFingerprint returns the value of Fingerprint.
func (s *AlertEvent) GetFingerprint() string {
	return s.Fingerprint
}

// GetName returns the value of Name.
func (s *AlertEvent) GetName() string {
	return s.Name
}

// GetStatus returns the value of Status.
func (s *AlertEvent) GetStatus() AlertEventStatus {
	return s.Status
}

// GetStartsAt returns the value of StartsAt.
func (s *AlertEvent) GetStartsAt() time.Time {
	return s.StartsAt
}

// GetEndsAt returns the value of EndsAt.
func (s *AlertEvent) GetEndsAt() OptDateTime {
	return s.EndsAt
}

// GetObservedAt returns the value of ObservedAt.
func (s *AlertEvent) GetObservedAt() time.Time {
	return s.ObservedAt
}

// SetID sets the value of ID.
func (s *AlertEvent) SetID(val int64) {
	s.ID = val
}

// SetFingerprint sets the value of Fingerprint.
func (s *AlertEvent) SetFingerprint(val string) {
	s.Fingerprint = val
}

// SetName sets the value of Name.
func (s *AlertEvent) SetName(val string) {
	s.Name = val
}

// SetStatus sets the value of Status.
func (s *AlertEvent) SetStatus(val AlertEventStatus) {
	s.Status = val
}

// SetStartsAt sets the value of StartsAt.
func (s *AlertEvent) SetStartsAt(val time.Time) {
	s.StartsAt = val
}

// SetEndsAt sets the value of EndsAt.
func (s *AlertEvent) SetEndsAt(val OptDateTime) {
	s.EndsAt = val
}

// SetObservedAt sets the value of ObservedAt.
func (s *AlertEvent) SetObservedAt(val time.Time) {
	s.ObservedAt = val
}

// The state the alert was seen in.
type AlertEventStatus string

const (
	AlertEventStatusFiring   AlertEventStatus = "firing"
	AlertEventStatusResolved AlertEventStatus = "resolved"
)

// AllValues returns all AlertEventStatus values.
func (AlertEventStatus) AllValues() []AlertEventStatus {
	return []AlertEventStatus{
		AlertEventStatusFiring,
		AlertEventStatusResolved,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AlertEventStatus) MarshalText() ([]byte, error) {
	switch s {
	case AlertEventStatusFiring:
		return []byte(s), nil
	case AlertEventStatusResolved:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AlertEventStatus) UnmarshalText(data []byte) error {
	switch AlertEventStatus(data) {
	case AlertEventStatusFiring:
		*s = AlertEventStatusFiring
		return nil
	case AlertEventStatusResolved:
		*s = AlertEventStatusResolved
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// A page of events, newest first.
// Ref: #/components/schemas/AlertHistory
type AlertHistory struct {
	// The events.
	Items []AlertEvent `json:"items"`
}

// GetItems returns the value of Items.
func (s *AlertHistory) GetItems() []AlertEvent {
	return s.Items
}

// SetItems sets the value of Items.
func (s *AlertHistory) SetItems(val []AlertEvent) {
	s.Items = val
}

func (*AlertHistory) listAlertHistoryRes() {}

// Every label of the alert.
type AlertLabels map[string]string

func (s *AlertLabels) init() AlertLabels {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// The alerts firing now, newest first.
// Ref: #/components/schemas/AlertList
type AlertList struct {
	// The alerts.
	Items []Alert `json:"items"`
}

// GetItems returns the value of Items.
func (s *AlertList) GetItems() []Alert {
	return s.Items
}

// SetItems sets the value of Items.
func (s *AlertList) SetItems(val []Alert) {
	s.Items = val
}

func (*AlertList) listAlertsRes() {}

// One commit that moved a pin.
// Ref: #/components/schemas/Deploy
type Deploy struct {
	// The commit.
	Commit string `json:"commit"`
	// When it was committed.
	At time.Time `json:"at"`
	// Its subject line.
	Message string `json:"message"`
}

// GetCommit returns the value of Commit.
func (s *Deploy) GetCommit() string {
	return s.Commit
}

// GetAt returns the value of At.
func (s *Deploy) GetAt() time.Time {
	return s.At
}

// GetMessage returns the value of Message.
func (s *Deploy) GetMessage() string {
	return s.Message
}

// SetCommit sets the value of Commit.
func (s *Deploy) SetCommit(val string) {
	s.Commit = val
}

// SetAt sets the value of At.
func (s *Deploy) SetAt(val time.Time) {
	s.At = val
}

// SetMessage sets the value of Message.
func (s *Deploy) SetMessage(val string) {
	s.Message = val
}

// A Project's deploys, newest first.
// Ref: #/components/schemas/DeployList
type DeployList struct {
	// The deploys.
	Items []Deploy `json:"items"`
}

// GetItems returns the value of Items.
func (s *DeployList) GetItems() []Deploy {
	return s.Items
}

// SetItems sets the value of Items.
func (s *DeployList) SetItems(val []Deploy) {
	s.Items = val
}

func (*DeployList) listDeploysRes() {}

// One open issue of the Estate repository.
// Ref: #/components/schemas/Issue
type Issue struct {
	// The issue number.
	Number int32 `json:"number"`
	// Its title.
	Title string `json:"title"`
	// Where it is on GitHub.
	URL string `json:"url"`
	// Its labels.
	Labels []string `json:"labels"`
	// When it last changed.
	UpdatedAt time.Time `json:"updatedAt"`
}

// GetNumber returns the value of Number.
func (s *Issue) GetNumber() int32 {
	return s.Number
}

// GetTitle returns the value of Title.
func (s *Issue) GetTitle() string {
	return s.Title
}

// GetURL returns the value of URL.
func (s *Issue) GetURL() string {
	return s.URL
}

// GetLabels returns the value of Labels.
func (s *Issue) GetLabels() []string {
	return s.Labels
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Issue) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetNumber sets the value of Number.
func (s *Issue) SetNumber(val int32) {
	s.Number = val
}

// SetTitle sets the value of Title.
func (s *Issue) SetTitle(val string) {
	s.Title = val
}

// SetURL sets the value of URL.
func (s *Issue) SetURL(val string) {
	s.URL = val
}

// SetLabels sets the value of Labels.
func (s *Issue) SetLabels(val []string) {
	s.Labels = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Issue) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// The open issues, most recently updated first.
// Ref: #/components/schemas/IssueList
type IssueList struct {
	// The issues.
	Items []Issue `json:"items"`
}

// GetItems returns the value of Items.
func (s *IssueList) GetItems() []Issue {
	return s.Items
}

// SetItems sets the value of Items.
func (s *IssueList) SetItems(val []Issue) {
	s.Items = val
}

func (*IssueList) listIssuesRes() {}

type ListAlertsServiceUnavailable ProblemStatusCode

func (*ListAlertsServiceUnavailable) listAlertsRes() {}

type ListAlertsUnauthorized ProblemStatusCode

func (*ListAlertsUnauthorized) listAlertsRes() {}

type ListDeploysServiceUnavailable ProblemStatusCode

func (*ListDeploysServiceUnavailable) listDeploysRes() {}

type ListDeploysUnauthorized ProblemStatusCode

func (*ListDeploysUnauthorized) listDeploysRes() {}

type ListIssuesServiceUnavailable ProblemStatusCode

func (*ListIssuesServiceUnavailable) listIssuesRes() {}

type ListIssuesUnauthorized ProblemStatusCode

func (*ListIssuesUnauthorized) listIssuesRes() {}

type ListPinsServiceUnavailable ProblemStatusCode

func (*ListPinsServiceUnavailable) listPinsRes() {}

type ListPinsUnauthorized ProblemStatusCode

func (*ListPinsUnauthorized) listPinsRes() {}

type ListReleasesServiceUnavailable ProblemStatusCode

func (*ListReleasesServiceUnavailable) listReleasesRes() {}

type ListReleasesUnauthorized ProblemStatusCode

func (*ListReleasesUnauthorized) listReleasesRes() {}

type ListSourcesServiceUnavailable ProblemStatusCode

func (*ListSourcesServiceUnavailable) listSourcesRes() {}

type ListSourcesUnauthorized ProblemStatusCode

func (*ListSourcesUnauthorized) listSourcesRes() {}

type ListUnitsServiceUnavailable ProblemStatusCode

func (*ListUnitsServiceUnavailable) listUnitsRes() {}

type ListUnitsUnauthorized ProblemStatusCode

func (*ListUnitsUnauthorized) listUnitsRes() {}

// One member of a gated Application, as Flagger switches it.
// Ref: #/components/schemas/Member
type Member struct {
	// The member Process.
	Process string `json:"process"`
	// Flagger's phase of its Canary; absent before Flagger has seen it.
	Phase OptString `json:"phase"`
	// The Application revision its Canary's webhooks carry.
	Revision OptString `json:"revision"`
	// The analysis iterations Flagger has counted.
	Iterations int32 `json:"iterations"`
}

// GetProcess returns the value of Process.
func (s *Member) GetProcess() string {
	return s.Process
}

// GetPhase returns the value of Phase.
func (s *Member) GetPhase() OptString {
	return s.Phase
}

// GetRevision returns the value of Revision.
func (s *Member) GetRevision() OptString {
	return s.Revision
}

// GetIterations returns the value of Iterations.
func (s *Member) GetIterations() int32 {
	return s.Iterations
}

// SetProcess sets the value of Process.
func (s *Member) SetProcess(val string) {
	s.Process = val
}

// SetPhase sets the value of Phase.
func (s *Member) SetPhase(val OptString) {
	s.Phase = val
}

// SetRevision sets the value of Revision.
func (s *Member) SetRevision(val OptString) {
	s.Revision = val
}

// SetIterations sets the value of Iterations.
func (s *Member) SetIterations(val int32) {
	s.Iterations = val
}

// NewOptAlertClass returns new OptAlertClass with value set to v.
func NewOptAlertClass(v AlertClass) OptAlertClass {
	return OptAlertClass{
		Value: v,
		Set:   true,
	}
}

// OptAlertClass is optional AlertClass.
type OptAlertClass struct {
	Value AlertClass
	Set   bool
}

// IsSet returns true if OptAlertClass was set.
func (o OptAlertClass) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAlertClass) Reset() {
	var v AlertClass
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAlertClass) SetTo(v AlertClass) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAlertClass) Get() (v AlertClass, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAlertClass) Or(d AlertClass) AlertClass {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPause returns new OptPause with value set to v.
func NewOptPause(v Pause) OptPause {
	return OptPause{
		Value: v,
		Set:   true,
	}
}

// OptPause is optional Pause.
type OptPause struct {
	Value Pause
	Set   bool
}

// IsSet returns true if OptPause was set.
func (o OptPause) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPause) Reset() {
	var v Pause
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPause) SetTo(v Pause) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPause) Get() (v Pause, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPause) Or(d Pause) Pause {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptReleaseMigration returns new OptReleaseMigration with value set to v.
func NewOptReleaseMigration(v ReleaseMigration) OptReleaseMigration {
	return OptReleaseMigration{
		Value: v,
		Set:   true,
	}
}

// OptReleaseMigration is optional ReleaseMigration.
type OptReleaseMigration struct {
	Value ReleaseMigration
	Set   bool
}

// IsSet returns true if OptReleaseMigration was set.
func (o OptReleaseMigration) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptReleaseMigration) Reset() {
	var v ReleaseMigration
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptReleaseMigration) SetTo(v ReleaseMigration) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptReleaseMigration) Get() (v ReleaseMigration, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptReleaseMigration) Or(d ReleaseMigration) ReleaseMigration {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRollback returns new OptRollback with value set to v.
func NewOptRollback(v Rollback) OptRollback {
	return OptRollback{
		Value: v,
		Set:   true,
	}
}

// OptRollback is optional Rollback.
type OptRollback struct {
	Value Rollback
	Set   bool
}

// IsSet returns true if OptRollback was set.
func (o OptRollback) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRollback) Reset() {
	var v Rollback
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRollback) SetTo(v Rollback) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRollback) Get() (v Rollback, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRollback) Or(d Rollback) Rollback {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// What a Pause or a Rollback recorded on a pin.
// Ref: #/components/schemas/Pause
type Pause struct {
	// The GitHub login that ran it.
	By string `json:"by"`
	// When, as recorded.
	At string `json:"at"`
	// The reason given.
	Reason string `json:"reason"`
}

// GetBy returns the value of By.
func (s *Pause) GetBy() string {
	return s.By
}

// GetAt returns the value of At.
func (s *Pause) GetAt() string {
	return s.At
}

// GetReason returns the value of Reason.
func (s *Pause) GetReason() string {
	return s.Reason
}

// SetBy sets the value of By.
func (s *Pause) SetBy(val string) {
	s.By = val
}

// SetAt sets the value of At.
func (s *Pause) SetAt(val string) {
	s.At = val
}

// SetReason sets the value of Reason.
func (s *Pause) SetReason(val string) {
	s.Reason = val
}

// One Project's pin.
// Ref: #/components/schemas/Pin
type Pin struct {
	// The Project.
	Project string `json:"project"`
	// The digest its source names; empty where the pin file holds no source.
	Digest     string      `json:"digest"`
	Paused     OptPause    `json:"paused"`
	RolledBack OptRollback `json:"rolledBack"`
}

// GetProject returns the value of Project.
func (s *Pin) GetProject() string {
	return s.Project
}

// GetDigest returns the value of Digest.
func (s *Pin) GetDigest() string {
	return s.Digest
}

// GetPaused returns the value of Paused.
func (s *Pin) GetPaused() OptPause {
	return s.Paused
}

// GetRolledBack returns the value of RolledBack.
func (s *Pin) GetRolledBack() OptRollback {
	return s.RolledBack
}

// SetProject sets the value of Project.
func (s *Pin) SetProject(val string) {
	s.Project = val
}

// SetDigest sets the value of Digest.
func (s *Pin) SetDigest(val string) {
	s.Digest = val
}

// SetPaused sets the value of Paused.
func (s *Pin) SetPaused(val OptPause) {
	s.Paused = val
}

// SetRolledBack sets the value of RolledBack.
func (s *Pin) SetRolledBack(val OptRollback) {
	s.RolledBack = val
}

// Every Project's pin, by Project.
// Ref: #/components/schemas/PinList
type PinList struct {
	// The pins.
	Items []Pin `json:"items"`
}

// GetItems returns the value of Items.
func (s *PinList) GetItems() []Pin {
	return s.Items
}

// SetItems sets the value of Items.
func (s *PinList) SetItems(val []Pin) {
	s.Items = val
}

func (*PinList) listPinsRes() {}

// An RFC 9457 problem detail.
// Ref: #/components/schemas/Problem
type Problem struct {
	// A URI naming the problem type.
	Type string `json:"type"`
	// A short summary of the problem type.
	Title string `json:"title"`
	// The HTTP status code.
	Status int32 `json:"status"`
	// What went wrong in this occurrence.
	Detail OptString `json:"detail"`
}

// GetType returns the value of Type.
func (s *Problem) GetType() string {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *Problem) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Problem) GetStatus() int32 {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *Problem) GetDetail() OptString {
	return s.Detail
}

// SetType sets the value of Type.
func (s *Problem) SetType(val string) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *Problem) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Problem) SetStatus(val int32) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *Problem) SetDetail(val OptString) {
	s.Detail = val
}

// ProblemStatusCode wraps Problem with StatusCode.
type ProblemStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *ProblemStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ProblemStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ProblemStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ProblemStatusCode) SetResponse(val Problem) {
	s.Response = val
}

func (*ProblemStatusCode) getSessionRes()       {}
func (*ProblemStatusCode) listAlertHistoryRes() {}

// One gated Application.
// Ref: #/components/schemas/Release
type Release struct {
	// The Application's namespace.
	Namespace string `json:"namespace"`
	// The Application.
	Application string `json:"application"`
	// Its members.
	Members   []Member            `json:"members"`
	Migration OptReleaseMigration `json:"migration"`
	// The revision the Release Gate recorded it serves; absent before it recorded one.
	Serving OptString `json:"serving"`
	// The revision the gate saw applied and not yet serving; absent when none is.
	Pinned OptString `json:"pinned"`
	// When the gate first saw the pinned revision.
	Since OptDateTime `json:"since"`
	// Why the rest of this release could not be read, where it could not: no inputs, inputs or a record
	// that do not parse, or more members than an Application has. Absent when it was read whole.
	Unreadable OptString `json:"unreadable"`
}

// GetNamespace returns the value of Namespace.
func (s *Release) GetNamespace() string {
	return s.Namespace
}

// GetApplication returns the value of Application.
func (s *Release) GetApplication() string {
	return s.Application
}

// GetMembers returns the value of Members.
func (s *Release) GetMembers() []Member {
	return s.Members
}

// GetMigration returns the value of Migration.
func (s *Release) GetMigration() OptReleaseMigration {
	return s.Migration
}

// GetServing returns the value of Serving.
func (s *Release) GetServing() OptString {
	return s.Serving
}

// GetPinned returns the value of Pinned.
func (s *Release) GetPinned() OptString {
	return s.Pinned
}

// GetSince returns the value of Since.
func (s *Release) GetSince() OptDateTime {
	return s.Since
}

// GetUnreadable returns the value of Unreadable.
func (s *Release) GetUnreadable() OptString {
	return s.Unreadable
}

// SetNamespace sets the value of Namespace.
func (s *Release) SetNamespace(val string) {
	s.Namespace = val
}

// SetApplication sets the value of Application.
func (s *Release) SetApplication(val string) {
	s.Application = val
}

// SetMembers sets the value of Members.
func (s *Release) SetMembers(val []Member) {
	s.Members = val
}

// SetMigration sets the value of Migration.
func (s *Release) SetMigration(val OptReleaseMigration) {
	s.Migration = val
}

// SetServing sets the value of Serving.
func (s *Release) SetServing(val OptString) {
	s.Serving = val
}

// SetPinned sets the value of Pinned.
func (s *Release) SetPinned(val OptString) {
	s.Pinned = val
}

// SetSince sets the value of Since.
func (s *Release) SetSince(val OptDateTime) {
	s.Since = val
}

// SetUnreadable sets the value of Unreadable.
func (s *Release) SetUnreadable(val OptString) {
	s.Unreadable = val
}

// The gated Applications.
// Ref: #/components/schemas/ReleaseList
type ReleaseList struct {
	// Whether the cluster holds more than one read returns. A read is bounded, so a cluster holding more
	// says so here rather than leaving the rest out unseen.
	Truncated bool `json:"truncated"`
	// The releases.
	Items []Release `json:"items"`
}

// GetTruncated returns the value of Truncated.
func (s *ReleaseList) GetTruncated() bool {
	return s.Truncated
}

// GetItems returns the value of Items.
func (s *ReleaseList) GetItems() []Release {
	return s.Items
}

// SetTruncated sets the value of Truncated.
func (s *ReleaseList) SetTruncated(val bool) {
	s.Truncated = val
}

// SetItems sets the value of Items.
func (s *ReleaseList) SetItems(val []Release) {
	s.Items = val
}

func (*ReleaseList) listReleasesRes() {}

// The migration the gate may start for a release.
// Ref: #/components/schemas/ReleaseMigration
type ReleaseMigration struct {
	// The identity its Jobs run as.
	Identity string `json:"identity"`
	// The serving revision the release was proven against; absent on a first release.
	TestedAgainst OptString `json:"testedAgainst"`
	// Whether a changeset of it cannot run in a transaction, which no undo touches.
	NonTransactional bool `json:"nonTransactional"`
}

// GetIdentity returns the value of Identity.
func (s *ReleaseMigration) GetIdentity() string {
	return s.Identity
}

// GetTestedAgainst returns the value of TestedAgainst.
func (s *ReleaseMigration) GetTestedAgainst() OptString {
	return s.TestedAgainst
}

// GetNonTransactional returns the value of NonTransactional.
func (s *ReleaseMigration) GetNonTransactional() bool {
	return s.NonTransactional
}

// SetIdentity sets the value of Identity.
func (s *ReleaseMigration) SetIdentity(val string) {
	s.Identity = val
}

// SetTestedAgainst sets the value of TestedAgainst.
func (s *ReleaseMigration) SetTestedAgainst(val OptString) {
	s.TestedAgainst = val
}

// SetNonTransactional sets the value of NonTransactional.
func (s *ReleaseMigration) SetNonTransactional(val bool) {
	s.NonTransactional = val
}

// The release a Rollback took the Project back to.
// Ref: #/components/schemas/Rollback
type Rollback struct {
	// The release version.
	Version string `json:"version"`
	// That release's fragment, by digest.
	Fragment string `json:"fragment"`
}

// GetVersion returns the value of Version.
func (s *Rollback) GetVersion() string {
	return s.Version
}

// GetFragment returns the value of Fragment.
func (s *Rollback) GetFragment() string {
	return s.Fragment
}

// SetVersion sets the value of Version.
func (s *Rollback) SetVersion(val string) {
	s.Version = val
}

// SetFragment sets the value of Fragment.
func (s *Rollback) SetFragment(val string) {
	s.Fragment = val
}

// The signed-in admin.
// Ref: #/components/schemas/Session
type Session struct {
	// The account's id in auth.
	Subject string `json:"subject"`
	// What to call the admin, which is the account's username.
	Name string `json:"name"`
}

// GetSubject returns the value of Subject.
func (s *Session) GetSubject() string {
	return s.Subject
}

// GetName returns the value of Name.
func (s *Session) GetName() string {
	return s.Name
}

// SetSubject sets the value of Subject.
func (s *Session) SetSubject(val string) {
	s.Subject = val
}

// SetName sets the value of Name.
func (s *Session) SetName(val string) {
	s.Name = val
}

func (*Session) getSessionRes() {}

type SessionCookie struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *SessionCookie) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *SessionCookie) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *SessionCookie) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *SessionCookie) SetRoles(val []string) {
	s.Roles = val
}

// A silence the dashboard set in Alertmanager.
// Ref: #/components/schemas/Silence
type Silence struct {
	// Alertmanager's id of the silence.
	ID string `json:"id"`
	// The silenced alert's fingerprint.
	Fingerprint string `json:"fingerprint"`
	// The admin who set it.
	CreatedBy string `json:"createdBy"`
	// When it was set.
	CreatedAt time.Time `json:"createdAt"`
	// When it ends. Absent on a silence that lasts until the alert resolves.
	EndsAt OptDateTime `json:"endsAt"`
}

// GetID returns the value of ID.
func (s *Silence) GetID() string {
	return s.ID
}

// GetFingerprint returns the value of Fingerprint.
func (s *Silence) GetFingerprint() string {
	return s.Fingerprint
}

// GetCreatedBy returns the value of CreatedBy.
func (s *Silence) GetCreatedBy() string {
	return s.CreatedBy
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Silence) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetEndsAt returns the value of EndsAt.
func (s *Silence) GetEndsAt() OptDateTime {
	return s.EndsAt
}

// SetID sets the value of ID.
func (s *Silence) SetID(val string) {
	s.ID = val
}

// SetFingerprint sets the value of Fingerprint.
func (s *Silence) SetFingerprint(val string) {
	s.Fingerprint = val
}

// SetCreatedBy sets the value of CreatedBy.
func (s *Silence) SetCreatedBy(val string) {
	s.CreatedBy = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Silence) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetEndsAt sets the value of EndsAt.
func (s *Silence) SetEndsAt(val OptDateTime) {
	s.EndsAt = val
}

func (*Silence) silenceAlertRes() {}

type SilenceAlertBadRequest ProblemStatusCode

func (*SilenceAlertBadRequest) silenceAlertRes() {}

type SilenceAlertNotFound ProblemStatusCode

func (*SilenceAlertNotFound) silenceAlertRes() {}

type SilenceAlertServiceUnavailable ProblemStatusCode

func (*SilenceAlertServiceUnavailable) silenceAlertRes() {}

// How long to silence an alert for.
// Ref: #/components/schemas/SilenceRequest
type SilenceRequest struct {
	// An hour, four hours, a day, or until the alert resolves.
	Length SilenceRequestLength `json:"length"`
}

// GetLength returns the value of Length.
func (s *SilenceRequest) GetLength() SilenceRequestLength {
	return s.Length
}

// SetLength sets the value of Length.
func (s *SilenceRequest) SetLength(val SilenceRequestLength) {
	s.Length = val
}

// An hour, four hours, a day, or until the alert resolves.
type SilenceRequestLength string

const (
	SilenceRequestLength1h            SilenceRequestLength = "1h"
	SilenceRequestLength4h            SilenceRequestLength = "4h"
	SilenceRequestLength1d            SilenceRequestLength = "1d"
	SilenceRequestLengthUntilResolved SilenceRequestLength = "until-resolved"
)

// AllValues returns all SilenceRequestLength values.
func (SilenceRequestLength) AllValues() []SilenceRequestLength {
	return []SilenceRequestLength{
		SilenceRequestLength1h,
		SilenceRequestLength4h,
		SilenceRequestLength1d,
		SilenceRequestLengthUntilResolved,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SilenceRequestLength) MarshalText() ([]byte, error) {
	switch s {
	case SilenceRequestLength1h:
		return []byte(s), nil
	case SilenceRequestLength4h:
		return []byte(s), nil
	case SilenceRequestLength1d:
		return []byte(s), nil
	case SilenceRequestLengthUntilResolved:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SilenceRequestLength) UnmarshalText(data []byte) error {
	switch SilenceRequestLength(data) {
	case SilenceRequestLength1h:
		*s = SilenceRequestLength1h
		return nil
	case SilenceRequestLength4h:
		*s = SilenceRequestLength4h
		return nil
	case SilenceRequestLength1d:
		*s = SilenceRequestLength1d
		return nil
	case SilenceRequestLengthUntilResolved:
		*s = SilenceRequestLengthUntilResolved
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// One Flux OCIRepository.
// Ref: #/components/schemas/Source
type Source struct {
	// The source's name, project- or estate.
	Name string `json:"name"`
	// The OCI repository of the artifact.
	URL string `json:"url"`
	// The digest the pin names; sixty-four zeros until the first publish.
	Digest string `json:"digest"`
	// What Flux last fetched, where it fetched anything.
	Revision OptString `json:"revision"`
	// Whether Flux reports the object Ready.
	Ready bool `json:"ready"`
	// The Ready condition's reason, where there is one.
	Reason OptString `json:"reason"`
	// The Ready condition's message, where there is one.
	Message OptString `json:"message"`
}

// GetName returns the value of Name.
func (s *Source) GetName() string {
	return s.Name
}

// GetURL returns the value of URL.
func (s *Source) GetURL() string {
	return s.URL
}

// GetDigest returns the value of Digest.
func (s *Source) GetDigest() string {
	return s.Digest
}

// GetRevision returns the value of Revision.
func (s *Source) GetRevision() OptString {
	return s.Revision
}

// GetReady returns the value of Ready.
func (s *Source) GetReady() bool {
	return s.Ready
}

// GetReason returns the value of Reason.
func (s *Source) GetReason() OptString {
	return s.Reason
}

// GetMessage returns the value of Message.
func (s *Source) GetMessage() OptString {
	return s.Message
}

// SetName sets the value of Name.
func (s *Source) SetName(val string) {
	s.Name = val
}

// SetURL sets the value of URL.
func (s *Source) SetURL(val string) {
	s.URL = val
}

// SetDigest sets the value of Digest.
func (s *Source) SetDigest(val string) {
	s.Digest = val
}

// SetRevision sets the value of Revision.
func (s *Source) SetRevision(val OptString) {
	s.Revision = val
}

// SetReady sets the value of Ready.
func (s *Source) SetReady(val bool) {
	s.Ready = val
}

// SetReason sets the value of Reason.
func (s *Source) SetReason(val OptString) {
	s.Reason = val
}

// SetMessage sets the value of Message.
func (s *Source) SetMessage(val OptString) {
	s.Message = val
}

// The pin sources, by name.
// Ref: #/components/schemas/SourceList
type SourceList struct {
	// Whether the cluster holds more than one read returns. A read is bounded, so a cluster holding more
	// says so here rather than leaving the rest out unseen.
	Truncated bool `json:"truncated"`
	// The sources.
	Items []Source `json:"items"`
}

// GetTruncated returns the value of Truncated.
func (s *SourceList) GetTruncated() bool {
	return s.Truncated
}

// GetItems returns the value of Items.
func (s *SourceList) GetItems() []Source {
	return s.Items
}

// SetTruncated sets the value of Truncated.
func (s *SourceList) SetTruncated(val bool) {
	s.Truncated = val
}

// SetItems sets the value of Items.
func (s *SourceList) SetItems(val []Source) {
	s.Items = val
}

func (*SourceList) listSourcesRes() {}

// One Flux Kustomization, one Reconcile Unit.
// Ref: #/components/schemas/Unit
type Unit struct {
	// The unit's name.
	Name string `json:"name"`
	// The source it applies from.
	Source string `json:"source"`
	// The directory of the artifact it applies.
	Path string `json:"path"`
	// The units it follows.
	DependsOn []string `json:"dependsOn"`
	// The source revision Flux last applied, where it applied anything.
	Applied OptString `json:"applied"`
	// Whether Flux reports the object Ready.
	Ready bool `json:"ready"`
	// The Ready condition's reason, where there is one.
	Reason OptString `json:"reason"`
	// The Ready condition's message, where there is one.
	Message OptString `json:"message"`
}

// GetName returns the value of Name.
func (s *Unit) GetName() string {
	return s.Name
}

// GetSource returns the value of Source.
func (s *Unit) GetSource() string {
	return s.Source
}

// GetPath returns the value of Path.
func (s *Unit) GetPath() string {
	return s.Path
}

// GetDependsOn returns the value of DependsOn.
func (s *Unit) GetDependsOn() []string {
	return s.DependsOn
}

// GetApplied returns the value of Applied.
func (s *Unit) GetApplied() OptString {
	return s.Applied
}

// GetReady returns the value of Ready.
func (s *Unit) GetReady() bool {
	return s.Ready
}

// GetReason returns the value of Reason.
func (s *Unit) GetReason() OptString {
	return s.Reason
}

// GetMessage returns the value of Message.
func (s *Unit) GetMessage() OptString {
	return s.Message
}

// SetName sets the value of Name.
func (s *Unit) SetName(val string) {
	s.Name = val
}

// SetSource sets the value of Source.
func (s *Unit) SetSource(val string) {
	s.Source = val
}

// SetPath sets the value of Path.
func (s *Unit) SetPath(val string) {
	s.Path = val
}

// SetDependsOn sets the value of DependsOn.
func (s *Unit) SetDependsOn(val []string) {
	s.DependsOn = val
}

// SetApplied sets the value of Applied.
func (s *Unit) SetApplied(val OptString) {
	s.Applied = val
}

// SetReady sets the value of Ready.
func (s *Unit) SetReady(val bool) {
	s.Ready = val
}

// SetReason sets the value of Reason.
func (s *Unit) SetReason(val OptString) {
	s.Reason = val
}

// SetMessage sets the value of Message.
func (s *Unit) SetMessage(val OptString) {
	s.Message = val
}

// The Reconcile Units, by name.
// Ref: #/components/schemas/UnitList
type UnitList struct {
	// Whether the cluster holds more than one read returns. A read is bounded, so a cluster holding more
	// says so here rather than leaving the rest out unseen.
	Truncated bool `json:"truncated"`
	// The units.
	Items []Unit `json:"items"`
}

// GetTruncated returns the value of Truncated.
func (s *UnitList) GetTruncated() bool {
	return s.Truncated
}

// GetItems returns the value of Items.
func (s *UnitList) GetItems() []Unit {
	return s.Items
}

// SetTruncated sets the value of Truncated.
func (s *UnitList) SetTruncated(val bool) {
	s.Truncated = val
}

// SetItems sets the value of Items.
func (s *UnitList) SetItems(val []Unit) {
	s.Items = val
}

func (*UnitList) listUnitsRes() {}
