// Code generated by ogen, DO NOT EDIT.
package oas

type GetSessionRes interface {
	getSessionRes()
}

type ListAlertHistoryRes interface {
	listAlertHistoryRes()
}

type ListAlertsRes interface {
	listAlertsRes()
}

type ListReleasesRes interface {
	listReleasesRes()
}

type ListSourcesRes interface {
	listSourcesRes()
}

type ListUnitsRes interface {
	listUnitsRes()
}

type SilenceAlertRes interface {
	silenceAlertRes()
}
