// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	GetSessionOperation       OperationName = "GetSession"
	ListAlertHistoryOperation OperationName = "ListAlertHistory"
	ListAlertsOperation       OperationName = "ListAlerts"
	ListDeploysOperation      OperationName = "ListDeploys"
	ListIssuesOperation       OperationName = "ListIssues"
	ListPinsOperation         OperationName = "ListPins"
	ListReleasesOperation     OperationName = "ListReleases"
	ListSourcesOperation      OperationName = "ListSources"
	ListUnitsOperation        OperationName = "ListUnits"
	SilenceAlertOperation     OperationName = "SilenceAlert"
)
