// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ListAlertHistory implements listAlertHistory operation.
	//
	// Returns at most `limit` events, newest first. An event is one state of one firing of an alert: it
	// fired, or it resolved. Alertmanager forgets a resolved alert; this is the dashboard's own record.
	//
	// GET /api/v1/alerts/history
	ListAlertHistory(ctx context.Context, params ListAlertHistoryParams) (ListAlertHistoryRes, error)
	// NewError creates *ProblemStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ProblemStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
