// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetSessionData, GetSessionErrors, GetSessionResponses, ListAlertHistoryData, ListAlertHistoryErrors, ListAlertHistoryResponses } from './types.gen';
import { zGetSessionResponse, zListAlertHistoryQuery, zListAlertHistoryResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Say who is signed in
 *
 * Returns the admin the session cookie belongs to. A request without a session, or with one auth no longer stands behind, gets a 401: the web app then shows the sign-in page.
 */
export const getSession = <ThrowOnError extends boolean = false>(options?: Options<GetSessionData, ThrowOnError>): RequestResult<GetSessionResponses, GetSessionErrors, ThrowOnError> => (options?.client ?? client).get<GetSessionResponses, GetSessionErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetSessionResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-estate_session',
            type: 'apiKey'
        }],
    url: '/api/v1/session',
    ...options
});

/**
 * List the states alerts were seen in, newest first
 *
 * Returns at most `limit` events, newest first. An event is one state of one firing of an alert: it fired, or it resolved. Alertmanager forgets a resolved alert; this is the dashboard's own record.
 */
export const listAlertHistory = <ThrowOnError extends boolean = false>(options?: Options<ListAlertHistoryData, ThrowOnError>): RequestResult<ListAlertHistoryResponses, ListAlertHistoryErrors, ThrowOnError> => (options?.client ?? client).get<ListAlertHistoryResponses, ListAlertHistoryErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: zListAlertHistoryQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zListAlertHistoryResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-estate_session',
            type: 'apiKey'
        }],
    url: '/api/v1/alerts/history',
    ...options
});
