// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetSessionData, GetSessionErrors, GetSessionResponses, ListAlertHistoryData, ListAlertHistoryErrors, ListAlertHistoryResponses, ListAlertsData, ListAlertsErrors, ListAlertsResponses, ListReleasesData, ListReleasesErrors, ListReleasesResponses, ListSourcesData, ListSourcesErrors, ListSourcesResponses, ListUnitsData, ListUnitsErrors, ListUnitsResponses, SilenceAlertData, SilenceAlertErrors, SilenceAlertResponses } from './types.gen';
import { zGetSessionResponse, zListAlertHistoryQuery, zListAlertHistoryResponse, zListAlertsResponse, zListReleasesResponse, zListSourcesResponse, zListUnitsResponse, zSilenceAlertBody, zSilenceAlertPath, zSilenceAlertResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Say who is signed in
 *
 * Returns the admin the session cookie belongs to. A request without a session, or with one auth no longer stands behind, gets a 401: the web app then shows the sign-in page.
 */
export const getSession = <ThrowOnError extends boolean = false>(options?: Options<GetSessionData, ThrowOnError>): RequestResult<GetSessionResponses, GetSessionErrors, ThrowOnError> => (options?.client ?? client).get<GetSessionResponses, GetSessionErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetSessionResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-estate_session',
            type: 'apiKey'
        }],
    url: '/api/v1/session',
    ...options
});

/**
 * List the alerts firing now, newest first
 *
 * Returns every alert Alertmanager holds now, silenced or not, newest first. Read from Alertmanager on every request; nothing here is copied into the dashboard's database. A 503 means Alertmanager did not answer.
 */
export const listAlerts = <ThrowOnError extends boolean = false>(options?: Options<ListAlertsData, ThrowOnError>): RequestResult<ListAlertsResponses, ListAlertsErrors, ThrowOnError> => (options?.client ?? client).get<ListAlertsResponses, ListAlertsErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zListAlertsResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-estate_session',
            type: 'apiKey'
        }],
    url: '/api/v1/alerts',
    ...options
});

/**
 * Silence an alert in Alertmanager
 *
 * Silences one firing alert, matching every one of its labels exactly, for an hour, four hours, a day, or until it resolves. The silence is set in Alertmanager, so Discord goes quiet too; it is the dashboard's only write. A silence until resolved lasts at most seven days in Alertmanager and is ended as soon as the dashboard sees the alert resolve. A 404 means the alert is not firing; a 503 that Alertmanager did not answer.
 */
export const silenceAlert = <ThrowOnError extends boolean = false>(options: Options<SilenceAlertData, ThrowOnError>): RequestResult<SilenceAlertResponses, SilenceAlertErrors, ThrowOnError> => (options.client ?? client).post<SilenceAlertResponses, SilenceAlertErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zSilenceAlertBody,
        path: zSilenceAlertPath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zSilenceAlertResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-estate_session',
            type: 'apiKey'
        }],
    url: '/api/v1/alerts/{fingerprint}/silences',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List the pin sources, by name
 *
 * Every Flux OCIRepository the render wrote: the artifact it names by digest, what Flux last fetched, and whether it is ready. A 503 means the cluster did not answer, or the dashboard runs without one.
 */
export const listSources = <ThrowOnError extends boolean = false>(options?: Options<ListSourcesData, ThrowOnError>): RequestResult<ListSourcesResponses, ListSourcesErrors, ThrowOnError> => (options?.client ?? client).get<ListSourcesResponses, ListSourcesErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zListSourcesResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-estate_session',
            type: 'apiKey'
        }],
    url: '/api/v1/delivery/sources',
    ...options
});

/**
 * List the Reconcile Units, by name
 *
 * Every Flux Kustomization the render wrote: its source, its path, the units it follows, what it last applied, and whether it is ready. A 503 means the cluster did not answer, or the dashboard runs without one.
 */
export const listUnits = <ThrowOnError extends boolean = false>(options?: Options<ListUnitsData, ThrowOnError>): RequestResult<ListUnitsResponses, ListUnitsErrors, ThrowOnError> => (options?.client ?? client).get<ListUnitsResponses, ListUnitsErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zListUnitsResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-estate_session',
            type: 'apiKey'
        }],
    url: '/api/v1/delivery/units',
    ...options
});

/**
 * List the gated Applications and their releases
 *
 * Every Application whose release-gate inputs the render wrote, by namespace and Application: each member as Flagger switches it, the migration the gate may start, and what the Release Gate recorded it serves and saw pinned. A 503 means the cluster did not answer, or the dashboard runs without one.
 */
export const listReleases = <ThrowOnError extends boolean = false>(options?: Options<ListReleasesData, ThrowOnError>): RequestResult<ListReleasesResponses, ListReleasesErrors, ThrowOnError> => (options?.client ?? client).get<ListReleasesResponses, ListReleasesErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zListReleasesResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-estate_session',
            type: 'apiKey'
        }],
    url: '/api/v1/delivery/releases',
    ...options
});

/**
 * List the states alerts were seen in, newest first
 *
 * Returns at most `limit` events, newest first. An event is one state of one firing of an alert: it fired, or it resolved. Alertmanager forgets a resolved alert; this is the dashboard's own record.
 */
export const listAlertHistory = <ThrowOnError extends boolean = false>(options?: Options<ListAlertHistoryData, ThrowOnError>): RequestResult<ListAlertHistoryResponses, ListAlertHistoryErrors, ThrowOnError> => (options?.client ?? client).get<ListAlertHistoryResponses, ListAlertHistoryErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: zListAlertHistoryQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zListAlertHistoryResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-estate_session',
            type: 'apiKey'
        }],
    url: '/api/v1/alerts/history',
    ...options
});
