// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://estate.jorisjonkers.dev' | (string & {});
};

/**
 * One Flux OCIRepository.
 */
export type Source = {
    /**
     * The source's name, project-<project> or estate.
     */
    name: string;
    /**
     * The OCI repository of the artifact.
     */
    url: string;
    /**
     * The digest the pin names; sixty-four zeros until the first publish.
     */
    digest: string;
    /**
     * What Flux last fetched, where it fetched anything.
     */
    revision?: string;
    /**
     * Whether Flux reports the object Ready.
     */
    ready: boolean;
    /**
     * The Ready condition's reason, where there is one.
     */
    reason?: string;
    /**
     * The Ready condition's message, where there is one.
     */
    message?: string;
};

/**
 * The pin sources, by name.
 */
export type SourceList = {
    /**
     * Whether the cluster holds more than one read returns. A read is bounded, so a cluster holding more says so here rather than leaving the rest out unseen.
     */
    truncated: boolean;
    /**
     * The sources.
     */
    items: Array<Source>;
};

/**
 * One Flux Kustomization, one Reconcile Unit.
 */
export type Unit = {
    /**
     * The unit's name.
     */
    name: string;
    /**
     * The source it applies from.
     */
    source: string;
    /**
     * The directory of the artifact it applies.
     */
    path: string;
    /**
     * The units it follows.
     */
    dependsOn: Array<string>;
    /**
     * The source revision Flux last applied, where it applied anything.
     */
    applied?: string;
    /**
     * Whether Flux reports the object Ready.
     */
    ready: boolean;
    /**
     * The Ready condition's reason, where there is one.
     */
    reason?: string;
    /**
     * The Ready condition's message, where there is one.
     */
    message?: string;
};

/**
 * The Reconcile Units, by name.
 */
export type UnitList = {
    /**
     * Whether the cluster holds more than one read returns. A read is bounded, so a cluster holding more says so here rather than leaving the rest out unseen.
     */
    truncated: boolean;
    /**
     * The units.
     */
    items: Array<Unit>;
};

/**
 * One member of a gated Application, as Flagger switches it.
 */
export type Member = {
    /**
     * The member Process.
     */
    process: string;
    /**
     * Flagger's phase of its Canary; absent before Flagger has seen it.
     */
    phase?: string;
    /**
     * The Application revision its Canary's webhooks carry.
     */
    revision?: string;
    /**
     * The analysis iterations Flagger has counted.
     */
    iterations: number;
};

/**
 * The migration the gate may start for a release.
 */
export type ReleaseMigration = {
    /**
     * The identity its Jobs run as.
     */
    identity: string;
    /**
     * The serving revision the release was proven against; absent on a first release.
     */
    testedAgainst?: string;
    /**
     * Whether a changeset of it cannot run in a transaction, which no undo touches.
     */
    nonTransactional: boolean;
};

/**
 * One gated Application.
 */
export type Release = {
    /**
     * The Application's namespace.
     */
    namespace: string;
    /**
     * The Application.
     */
    application: string;
    /**
     * Its members.
     */
    members: Array<Member>;
    migration?: ReleaseMigration;
    /**
     * The revision the Release Gate recorded it serves; absent before it recorded one.
     */
    serving?: string;
    /**
     * The revision the gate saw applied and not yet serving; absent when none is.
     */
    pinned?: string;
    /**
     * When the gate first saw the pinned revision.
     */
    since?: string;
    /**
     * Why the rest of this release could not be read, where it could not: no inputs, inputs or a record that do not parse, or more members than an Application has. Absent when it was read whole.
     */
    unreadable?: string;
};

/**
 * The gated Applications.
 */
export type ReleaseList = {
    /**
     * Whether the cluster holds more than one read returns. A read is bounded, so a cluster holding more says so here rather than leaving the rest out unseen.
     */
    truncated: boolean;
    /**
     * The releases.
     */
    items: Array<Release>;
};

/**
 * One alert Alertmanager holds now.
 */
export type Alert = {
    /**
     * Alertmanager's fingerprint of the alert.
     */
    fingerprint: string;
    /**
     * The alert's name, its alertname label.
     */
    name: string;
    /**
     * How loudly the alert wakes someone, from its alert_class label. Absent on an alert whose rule carries no class the dashboard knows.
     */
    class?: 'business-hours' | 'urgent' | 'page';
    /**
     * The rule's summary annotation, where it carries one.
     */
    summary?: string;
    /**
     * When this firing of the alert started.
     */
    startsAt: string;
    /**
     * Every label of the alert.
     */
    labels: {
        [key: string]: string;
    };
    /**
     * The id of every silence that holds the alert quiet now; empty when none does.
     */
    silencedBy: Array<string>;
};

/**
 * The alerts firing now, newest first.
 */
export type AlertList = {
    /**
     * The alerts.
     */
    items: Array<Alert>;
};

/**
 * How long to silence an alert for.
 */
export type SilenceRequest = {
    /**
     * An hour, four hours, a day, or until the alert resolves.
     */
    length: '1h' | '4h' | '1d' | 'until-resolved';
};

/**
 * A silence the dashboard set in Alertmanager.
 */
export type Silence = {
    /**
     * Alertmanager's id of the silence.
     */
    id: string;
    /**
     * The silenced alert's fingerprint.
     */
    fingerprint: string;
    /**
     * The admin who set it.
     */
    createdBy: string;
    /**
     * When it was set.
     */
    createdAt: string;
    /**
     * When it ends. Absent on a silence that lasts until the alert resolves.
     */
    endsAt?: string;
};

/**
 * One state an alert was seen in.
 */
export type AlertEvent = {
    /**
     * The event's id.
     */
    id: number;
    /**
     * Alertmanager's fingerprint of the alert.
     */
    fingerprint: string;
    /**
     * The alert's name.
     */
    name: string;
    /**
     * The state the alert was seen in.
     */
    status: 'firing' | 'resolved';
    /**
     * When this firing of the alert started.
     */
    startsAt: string;
    /**
     * When the alert resolved. Present exactly when the status is resolved.
     */
    endsAt?: string;
    /**
     * When the dashboard saw the alert in this state.
     */
    observedAt: string;
};

/**
 * The signed-in admin.
 */
export type Session = {
    /**
     * The account's id in auth.
     */
    subject: string;
    /**
     * What to call the admin, which is the account's username.
     */
    name: string;
};

/**
 * A page of events, newest first.
 */
export type AlertHistory = {
    /**
     * The events.
     */
    items: Array<AlertEvent>;
};

/**
 * An RFC 9457 problem detail.
 */
export type Problem = {
    /**
     * A URI naming the problem type.
     */
    type: string;
    /**
     * A short summary of the problem type.
     */
    title: string;
    /**
     * The HTTP status code.
     */
    status: number;
    /**
     * What went wrong in this occurrence.
     */
    detail?: string;
};

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/session';
};

export type GetSessionErrors = {
    /**
     * An RFC 9457 problem.
     */
    401: Problem;
    /**
     * An RFC 9457 problem.
     */
    default: Problem;
};

export type GetSessionError = GetSessionErrors[keyof GetSessionErrors];

export type GetSessionResponses = {
    /**
     * The signed-in admin.
     */
    200: Session;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type ListAlertsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/alerts';
};

export type ListAlertsErrors = {
    /**
     * An RFC 9457 problem.
     */
    401: Problem;
    /**
     * An RFC 9457 problem.
     */
    503: Problem;
    /**
     * An RFC 9457 problem.
     */
    default: Problem;
};

export type ListAlertsError = ListAlertsErrors[keyof ListAlertsErrors];

export type ListAlertsResponses = {
    /**
     * The alerts.
     */
    200: AlertList;
};

export type ListAlertsResponse = ListAlertsResponses[keyof ListAlertsResponses];

export type SilenceAlertData = {
    body: SilenceRequest;
    path: {
        /**
         * Alertmanager's fingerprint of the alert.
         */
        fingerprint: string;
    };
    query?: never;
    url: '/api/v1/alerts/{fingerprint}/silences';
};

export type SilenceAlertErrors = {
    /**
     * An RFC 9457 problem.
     */
    400: Problem;
    /**
     * An RFC 9457 problem.
     */
    404: Problem;
    /**
     * An RFC 9457 problem.
     */
    503: Problem;
    /**
     * An RFC 9457 problem.
     */
    default: Problem;
};

export type SilenceAlertError = SilenceAlertErrors[keyof SilenceAlertErrors];

export type SilenceAlertResponses = {
    /**
     * The silence Alertmanager now holds.
     */
    201: Silence;
};

export type SilenceAlertResponse = SilenceAlertResponses[keyof SilenceAlertResponses];

export type ListSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/delivery/sources';
};

export type ListSourcesErrors = {
    /**
     * An RFC 9457 problem.
     */
    401: Problem;
    /**
     * An RFC 9457 problem.
     */
    503: Problem;
    /**
     * An RFC 9457 problem.
     */
    default: Problem;
};

export type ListSourcesError = ListSourcesErrors[keyof ListSourcesErrors];

export type ListSourcesResponses = {
    /**
     * What the cluster holds.
     */
    200: SourceList;
};

export type ListSourcesResponse = ListSourcesResponses[keyof ListSourcesResponses];

export type ListUnitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/delivery/units';
};

export type ListUnitsErrors = {
    /**
     * An RFC 9457 problem.
     */
    401: Problem;
    /**
     * An RFC 9457 problem.
     */
    503: Problem;
    /**
     * An RFC 9457 problem.
     */
    default: Problem;
};

export type ListUnitsError = ListUnitsErrors[keyof ListUnitsErrors];

export type ListUnitsResponses = {
    /**
     * What the cluster holds.
     */
    200: UnitList;
};

export type ListUnitsResponse = ListUnitsResponses[keyof ListUnitsResponses];

export type ListReleasesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/delivery/releases';
};

export type ListReleasesErrors = {
    /**
     * An RFC 9457 problem.
     */
    401: Problem;
    /**
     * An RFC 9457 problem.
     */
    503: Problem;
    /**
     * An RFC 9457 problem.
     */
    default: Problem;
};

export type ListReleasesError = ListReleasesErrors[keyof ListReleasesErrors];

export type ListReleasesResponses = {
    /**
     * What the cluster holds.
     */
    200: ReleaseList;
};

export type ListReleasesResponse = ListReleasesResponses[keyof ListReleasesResponses];

export type ListAlertHistoryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * How many events to return.
         */
        limit?: number;
    };
    url: '/api/v1/alerts/history';
};

export type ListAlertHistoryErrors = {
    /**
     * An RFC 9457 problem.
     */
    400: Problem;
    /**
     * An RFC 9457 problem.
     */
    default: Problem;
};

export type ListAlertHistoryError = ListAlertHistoryErrors[keyof ListAlertHistoryErrors];

export type ListAlertHistoryResponses = {
    /**
     * The events.
     */
    200: AlertHistory;
};

export type ListAlertHistoryResponse = ListAlertHistoryResponses[keyof ListAlertHistoryResponses];
