// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * One alert Alertmanager holds now.
 */
export const zAlert = z.object({
    fingerprint: z.string().min(1).max(64),
    name: z.string().min(1).max(255),
    class: z.enum([
        'business-hours',
        'urgent',
        'page'
    ]).optional(),
    summary: z.string().max(1024).optional(),
    startsAt: z.iso.datetime({ offset: true }).max(64),
    labels: z.record(z.string(), z.string().max(1024)),
    silencedBy: z.array(z.string().min(1).max(64)).max(64)
});

/**
 * The alerts firing now, newest first.
 */
export const zAlertList = z.object({
    items: z.array(zAlert).max(1000)
});

/**
 * How long to silence an alert for.
 */
export const zSilenceRequest = z.object({
    length: z.enum([
        '1h',
        '4h',
        '1d',
        'until-resolved'
    ])
});

/**
 * A silence the dashboard set in Alertmanager.
 */
export const zSilence = z.object({
    id: z.string().min(1).max(64),
    fingerprint: z.string().min(1).max(64),
    createdBy: z.string().min(1).max(255),
    createdAt: z.iso.datetime({ offset: true }).max(64),
    endsAt: z.iso.datetime({ offset: true }).max(64).optional()
});

/**
 * One state an alert was seen in.
 */
export const zAlertEvent = z.object({
    id: z.coerce.bigint().gte(BigInt(1)).lte(BigInt(9223372036854776000)),
    fingerprint: z.string().min(1).max(64),
    name: z.string().min(1).max(255),
    status: z.enum(['firing', 'resolved']),
    startsAt: z.iso.datetime({ offset: true }).max(64),
    endsAt: z.iso.datetime({ offset: true }).max(64).optional(),
    observedAt: z.iso.datetime({ offset: true }).max(64)
});

/**
 * The signed-in admin.
 */
export const zSession = z.object({
    subject: z.string().min(1).max(255),
    name: z.string().min(1).max(255)
});

/**
 * A page of events, newest first.
 */
export const zAlertHistory = z.object({
    items: z.array(zAlertEvent).max(100)
});

/**
 * An RFC 9457 problem detail.
 */
export const zProblem = z.object({
    type: z.string().max(256),
    title: z.string().max(256),
    status: z.int().gte(100).lte(599),
    detail: z.string().max(1024).optional()
});

/**
 * The signed-in admin.
 */
export const zGetSessionResponse = zSession;

/**
 * The alerts.
 */
export const zListAlertsResponse = zAlertList;

export const zSilenceAlertBody = zSilenceRequest;

export const zSilenceAlertPath = z.object({
    fingerprint: z.string().min(1).max(64).regex(/^[0-9a-f]+$/)
});

/**
 * The silence Alertmanager now holds.
 */
export const zSilenceAlertResponse = zSilence;

export const zListAlertHistoryQuery = z.object({
    limit: z.int().gte(1).lte(100).optional().default(50)
});

/**
 * The events.
 */
export const zListAlertHistoryResponse = zAlertHistory;
