// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * What a Pause or a Rollback recorded on a pin.
 */
export const zPause = z.object({
    by: z.string().max(255),
    at: z.string().max(64),
    reason: z.string().max(1024)
});

/**
 * The release a Rollback took the Project back to.
 */
export const zRollback = z.object({
    version: z.string().max(64),
    fragment: z.string().max(256)
});

/**
 * One Project's pin.
 */
export const zPin = z.object({
    project: z.string().min(1).max(63),
    digest: z.string().max(128),
    paused: zPause.optional(),
    rolledBack: zRollback.optional()
});

/**
 * Every Project's pin, by Project.
 */
export const zPinList = z.object({
    items: z.array(zPin).max(1000)
});

/**
 * One commit that moved a pin.
 */
export const zDeploy = z.object({
    commit: z.string().min(1).max(64),
    at: z.iso.datetime({ offset: true }).max(64),
    message: z.string().max(1024)
});

/**
 * A Project's deploys, newest first.
 */
export const zDeployList = z.object({
    items: z.array(zDeploy).max(100)
});

/**
 * One open issue of the Estate repository.
 */
export const zIssue = z.object({
    number: z.int().gte(1).lte(2147483647),
    title: z.string().max(1024),
    url: z.string().max(1024),
    labels: z.array(z.string().max(255)).max(100),
    updatedAt: z.iso.datetime({ offset: true }).max(64)
});

/**
 * The open issues, most recently updated first.
 */
export const zIssueList = z.object({
    items: z.array(zIssue).max(100)
});

/**
 * One Flux OCIRepository.
 */
export const zSource = z.object({
    name: z.string().min(1).max(253),
    url: z.string().max(1024),
    digest: z.string().max(128),
    revision: z.string().max(128).optional(),
    ready: z.boolean(),
    reason: z.string().max(256).optional(),
    message: z.string().max(4096).optional()
});

/**
 * The pin sources, by name.
 */
export const zSourceList = z.object({
    truncated: z.boolean(),
    items: z.array(zSource).max(1000)
});

/**
 * One Flux Kustomization, one Reconcile Unit.
 */
export const zUnit = z.object({
    name: z.string().min(1).max(253),
    source: z.string().max(253),
    path: z.string().max(1024),
    dependsOn: z.array(z.string().max(253)).max(256),
    applied: z.string().max(128).optional(),
    ready: z.boolean(),
    reason: z.string().max(256).optional(),
    message: z.string().max(4096).optional()
});

/**
 * The Reconcile Units, by name.
 */
export const zUnitList = z.object({
    truncated: z.boolean(),
    items: z.array(zUnit).max(1000)
});

/**
 * One member of a gated Application, as Flagger switches it.
 */
export const zMember = z.object({
    process: z.string().min(1).max(253),
    phase: z.string().max(64).optional(),
    revision: z.string().max(128).optional(),
    iterations: z.int().gte(0).lte(1000000)
});

/**
 * The migration the gate may start for a release.
 */
export const zReleaseMigration = z.object({
    identity: z.string().min(1).max(253),
    testedAgainst: z.string().max(128).optional(),
    nonTransactional: z.boolean()
});

/**
 * One gated Application.
 */
export const zRelease = z.object({
    namespace: z.string().min(1).max(63),
    application: z.string().min(1).max(253),
    members: z.array(zMember).max(64),
    migration: zReleaseMigration.optional(),
    serving: z.string().max(128).optional(),
    pinned: z.string().max(128).optional(),
    since: z.iso.datetime({ offset: true }).max(64).optional(),
    unreadable: z.string().max(256).optional()
});

/**
 * The gated Applications.
 */
export const zReleaseList = z.object({
    truncated: z.boolean(),
    items: z.array(zRelease).max(1000)
});

/**
 * One alert Alertmanager holds now.
 */
export const zAlert = z.object({
    fingerprint: z.string().min(1).max(64),
    name: z.string().min(1).max(255),
    class: z.enum([
        'business-hours',
        'urgent',
        'page'
    ]).optional(),
    summary: z.string().max(1024).optional(),
    startsAt: z.iso.datetime({ offset: true }).max(64),
    labels: z.record(z.string(), z.string().max(1024)),
    silencedBy: z.array(z.string().min(1).max(64)).max(64)
});

/**
 * The alerts firing now, newest first.
 */
export const zAlertList = z.object({
    items: z.array(zAlert).max(1000)
});

/**
 * How long to silence an alert for.
 */
export const zSilenceRequest = z.object({
    length: z.enum([
        '1h',
        '4h',
        '1d',
        'until-resolved'
    ])
});

/**
 * A silence the dashboard set in Alertmanager.
 */
export const zSilence = z.object({
    id: z.string().min(1).max(64),
    fingerprint: z.string().min(1).max(64),
    createdBy: z.string().min(1).max(255),
    createdAt: z.iso.datetime({ offset: true }).max(64),
    endsAt: z.iso.datetime({ offset: true }).max(64).optional()
});

/**
 * One state an alert was seen in.
 */
export const zAlertEvent = z.object({
    id: z.coerce.bigint().gte(BigInt(1)).lte(BigInt(9223372036854776000)),
    fingerprint: z.string().min(1).max(64),
    name: z.string().min(1).max(255),
    status: z.enum(['firing', 'resolved']),
    startsAt: z.iso.datetime({ offset: true }).max(64),
    endsAt: z.iso.datetime({ offset: true }).max(64).optional(),
    observedAt: z.iso.datetime({ offset: true }).max(64)
});

/**
 * The signed-in admin.
 */
export const zSession = z.object({
    subject: z.string().min(1).max(255),
    name: z.string().min(1).max(255)
});

/**
 * A page of events, newest first.
 */
export const zAlertHistory = z.object({
    items: z.array(zAlertEvent).max(100)
});

/**
 * An RFC 9457 problem detail.
 */
export const zProblem = z.object({
    type: z.string().max(256),
    title: z.string().max(256),
    status: z.int().gte(100).lte(599),
    detail: z.string().max(1024).optional()
});

/**
 * The signed-in admin.
 */
export const zGetSessionResponse = zSession;

/**
 * The alerts.
 */
export const zListAlertsResponse = zAlertList;

export const zSilenceAlertBody = zSilenceRequest;

export const zSilenceAlertPath = z.object({
    fingerprint: z.string().min(1).max(64).regex(/^[0-9a-f]+$/)
});

/**
 * The silence Alertmanager now holds.
 */
export const zSilenceAlertResponse = zSilence;

/**
 * What the Estate repository holds.
 */
export const zListPinsResponse = zPinList;

export const zListDeploysPath = z.object({
    project: z.string().min(1).max(63).regex(/^[a-z0-9_][a-z0-9_-]{0,62}$/)
});

export const zListDeploysQuery = z.object({
    limit: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * What the Estate repository holds.
 */
export const zListDeploysResponse = zDeployList;

/**
 * What the Estate repository holds.
 */
export const zListIssuesResponse = zIssueList;

/**
 * What the cluster holds.
 */
export const zListSourcesResponse = zSourceList;

/**
 * What the cluster holds.
 */
export const zListUnitsResponse = zUnitList;

/**
 * What the cluster holds.
 */
export const zListReleasesResponse = zReleaseList;

export const zListAlertHistoryQuery = z.object({
    limit: z.int().gte(1).lte(100).optional().default(50)
});

/**
 * The events.
 */
export const zListAlertHistoryResponse = zAlertHistory;
