// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
)

type Querier interface {
	ListAlertHistory(ctx context.Context, limit int32) ([]ListAlertHistoryRow, error)
}

var _ Querier = (*Queries)(nil)
